type: object
properties:
    paths:
        $ref: "#/$defs/Paths"
    instances:
        type: array
        items:
            $ref: "#/$defs/Instance"
    defaults:
        $ref: "#/$defs/Defaults"
required:
    - paths
    - defaults
unevaluatedProperties: false
additionalProperties: false


#=====
# Types
$defs:

#-----
# Type: Paths
    Paths:
        type: object
        properties:
            jboss:
                type: string
            instances:
                type: string
            run:
                type: string
        required:
            - jboss
            - instances
            - run
        unevaluatedProperties: false
        additionalProperties: false


#-----
# Type: Instance
    Instance:
        type: object
        properties:
            jvm:
                $ref: "#/$defs/Defaults-JVM"


#-----
# Type: Defaults
    Defaults:
        type: object
        properties:
            jboss:
                $ref: "#/$defs/Defaults-JBoss"
            jvm:
                $ref: "#/$defs/Defaults-JVM"
        required:
            - jboss
        unevaluatedProperties: false
        additionalProperties: false


#-----
# Type: Defaults-JBoss
    Defaults-JBoss:
        type: object
        properties:
            profile:
                type: string
            # TODO extract`properties` inlined type to referencable type `JBoss-Properties`
            properties:
                type: object
                properties:
                    /:
                        type: string
                patternProperties:
                   ^jboss.([a-z]+)((.[a-z]+)*)$:
                         type: string
                not:
                    anyOf:
                        - required:
                            - jboss.server.base.dir
                        - required:
                            - jboss.server.default.config
                unevaluatedProperties: false
                additionalProperties: false
        required:
            - profile
        unevaluatedProperties: false
        additionalProperties: false


#-----
# Type: Defaults-JVM
# TODO Change this name to `JVM-Options``
    Defaults-JVM:
        type: object
        properties:
            options:
                type: object
                properties:
                    /: {}
