# Reference: https://json-schema.org/
type: object
properties:
    paths:
        $ref: "#/$defs/Paths"
    instances:
        type: array
        items:
            $ref: "#/$defs/Instance"
    defaults:
        $ref: "#/$defs/Defaults"
required:
    - paths
    - defaults
unevaluatedProperties: false
additionalProperties: false


#=====
# Types
$defs:

#-----
# Type: Paths
    Paths:
        type: object
        properties:
            jboss:
                type: string
            instances:
                type: string
            run:
                type: string
        required:
            - jboss
            - instances
            - run
        unevaluatedProperties: false
        additionalProperties: false


#-----
# Type: Instance
#       TODO `jboss` properties should be here too via type `JBoss-Properties`
    Instance:
        type: object
        properties:
            name:
                type: string
            jvm:
                $ref: "#/$defs/JVM-Options"
            java:
                $ref: "#/$defs/JVM-Properties"
        required:
            - name
        unevaluatedProperties: false
        additionalProperties: false


#-----
# Type: Defaults
    Defaults:
        type: object
        properties:
            jboss:
                $ref: "#/$defs/Defaults-JBoss"
            jvm:
                $ref: "#/$defs/JVM-Options"
            java:
                $ref: "#/$defs/JVM-Properties"
        required:
            - jboss
        unevaluatedProperties: false
        additionalProperties: false


#-----
# Type: Defaults-JBoss
    Defaults-JBoss:
        type: object
        properties:
            profile:
                type: string
            properties:
                $ref: "#/$defs/JBoss-Properties"
        required:
            - profile
        unevaluatedProperties: false
        additionalProperties: false


#-----
# Type: JBoss-Properties
    JBoss-Properties:
        type: object
        properties:
            /:
                type: string
        patternProperties:
            ^jboss.([a-z]+)((.[a-z]+)*)$:
                type: string
        not:
            anyOf:
                - required:
                    - jboss.server.base.dir
                - required:
                    - jboss.server.default.config
        unevaluatedProperties: false
        additionalProperties: false


#-----
# Type: JVM-Options
    JVM-Options:
        type: object
        properties:
            options:
                type: object
                properties:
                    /: {}


#-----
# Type: JVM-Properties
    JVM-Properties:
        type: object
        properties:
            properties:
                type: object
                properties:
                    /: {}
